<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1496309864623" stop="1496309864771">
  <name>initTest</name>
  <labels/>
  <test-cases>
    <test-case start="1496309864623" status="failed" stop="1496309864710">
      <name>test_case_login[-1-'NoneType' object has no attribute 'status_code':\u672a\u77e5\u9519\u8bef(\u63a5\u53e3\u8bf7\u6c42\u8d85\u65f6\u6216\u4f20\u9012\u6570\u636e\u9519\u8bef\u7b49)-200.0-Operation is successful.-\u767b\u5f55\u6210\u529f]</name>
      <failure>
        <message>AssertionError: assert -1 == 200.0</message>
        <stack-trace>act_code = -1
act_msg = "'NoneType' object has no attribute 'status_code':未知错误(接口请求超时或传递数据错误等)"
exp_code = 200.0, exp_msg = 'Operation is successful.', case_name = '登录成功'

    @allure.feature(sheet.name)  # @allure.feature('（Feature1特征）')
    @pytest.mark.parametrize('act_code, act_msg, exp_code, exp_msg, case_name', ResultParam(idx).value)
    def test_fn(act_code, act_msg, exp_code, exp_msg, case_name):
&gt;       assert act_code == exp_code
E       assert -1 == 200.0

initTest.py:21: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="feature" value="login"/>
        <label name="severity" value="normal"/>
        <label name="thread" value="4244-MainThread"/>
        <label name="host" value="USER-20150424AG"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1496309864716" status="failed" stop="1496309864722">
      <name>test_case_login[-1-'NoneType' object has no attribute 'status_code':\u672a\u77e5\u9519\u8bef(\u63a5\u53e3\u8bf7\u6c42\u8d85\u65f6\u6216\u4f20\u9012\u6570\u636e\u9519\u8bef\u7b49)-220.0-Invalid account and.or password.-\u7528\u6237\u540d\u9519\u8bef]</name>
      <failure>
        <message>AssertionError: assert -1 == 220.0</message>
        <stack-trace>act_code = -1
act_msg = "'NoneType' object has no attribute 'status_code':未知错误(接口请求超时或传递数据错误等)"
exp_code = 220.0, exp_msg = 'Invalid account and/or password.'
case_name = '用户名错误'

    @allure.feature(sheet.name)  # @allure.feature('（Feature1特征）')
    @pytest.mark.parametrize('act_code, act_msg, exp_code, exp_msg, case_name', ResultParam(idx).value)
    def test_fn(act_code, act_msg, exp_code, exp_msg, case_name):
&gt;       assert act_code == exp_code
E       assert -1 == 220.0

initTest.py:21: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="feature" value="login"/>
        <label name="severity" value="normal"/>
        <label name="thread" value="4244-MainThread"/>
        <label name="host" value="USER-20150424AG"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1496309864723" status="failed" stop="1496309864729">
      <name>test_case_login[-1-'NoneType' object has no attribute 'status_code':\u672a\u77e5\u9519\u8bef(\u63a5\u53e3\u8bf7\u6c42\u8d85\u65f6\u6216\u4f20\u9012\u6570\u636e\u9519\u8bef\u7b49)-220.0-Invalid account and.or password.-\u5bc6\u7801\u9519\u8bef]</name>
      <failure>
        <message>AssertionError: assert -1 == 220.0</message>
        <stack-trace>act_code = -1
act_msg = "'NoneType' object has no attribute 'status_code':未知错误(接口请求超时或传递数据错误等)"
exp_code = 220.0, exp_msg = 'Invalid account and/or password.'
case_name = '密码错误'

    @allure.feature(sheet.name)  # @allure.feature('（Feature1特征）')
    @pytest.mark.parametrize('act_code, act_msg, exp_code, exp_msg, case_name', ResultParam(idx).value)
    def test_fn(act_code, act_msg, exp_code, exp_msg, case_name):
&gt;       assert act_code == exp_code
E       assert -1 == 220.0

initTest.py:21: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="feature" value="login"/>
        <label name="severity" value="normal"/>
        <label name="thread" value="4244-MainThread"/>
        <label name="host" value="USER-20150424AG"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1496309864729" status="failed" stop="1496309864734">
      <name>test_case_login[-1-'NoneType' object has no attribute 'status_code':\u672a\u77e5\u9519\u8bef(\u63a5\u53e3\u8bf7\u6c42\u8d85\u65f6\u6216\u4f20\u9012\u6570\u636e\u9519\u8bef\u7b49)-220.0-Invalid account and.or password.-\u7528\u6237\u540d\u672a\u6fc0\u6d3b]</name>
      <failure>
        <message>AssertionError: assert -1 == 220.0</message>
        <stack-trace>act_code = -1
act_msg = "'NoneType' object has no attribute 'status_code':未知错误(接口请求超时或传递数据错误等)"
exp_code = 220.0, exp_msg = 'Invalid account and/or password.'
case_name = '用户名未激活'

    @allure.feature(sheet.name)  # @allure.feature('（Feature1特征）')
    @pytest.mark.parametrize('act_code, act_msg, exp_code, exp_msg, case_name', ResultParam(idx).value)
    def test_fn(act_code, act_msg, exp_code, exp_msg, case_name):
&gt;       assert act_code == exp_code
E       assert -1 == 220.0

initTest.py:21: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="feature" value="login"/>
        <label name="severity" value="normal"/>
        <label name="thread" value="4244-MainThread"/>
        <label name="host" value="USER-20150424AG"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1496309864735" status="failed" stop="1496309864741">
      <name>test_case_login[-1-'NoneType' object has no attribute 'status_code':\u672a\u77e5\u9519\u8bef(\u63a5\u53e3\u8bf7\u6c42\u8d85\u65f6\u6216\u4f20\u9012\u6570\u636e\u9519\u8bef\u7b49)-400.0-Invalid request data format.-\u7528\u6237\u540d\u4e3anone]</name>
      <failure>
        <message>AssertionError: assert -1 == 400.0</message>
        <stack-trace>act_code = -1
act_msg = "'NoneType' object has no attribute 'status_code':未知错误(接口请求超时或传递数据错误等)"
exp_code = 400.0, exp_msg = 'Invalid request data format.'
case_name = '用户名为none'

    @allure.feature(sheet.name)  # @allure.feature('（Feature1特征）')
    @pytest.mark.parametrize('act_code, act_msg, exp_code, exp_msg, case_name', ResultParam(idx).value)
    def test_fn(act_code, act_msg, exp_code, exp_msg, case_name):
&gt;       assert act_code == exp_code
E       assert -1 == 400.0

initTest.py:21: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="feature" value="login"/>
        <label name="severity" value="normal"/>
        <label name="thread" value="4244-MainThread"/>
        <label name="host" value="USER-20150424AG"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1496309864742" status="failed" stop="1496309864747">
      <name>test_case_login[-1-'NoneType' object has no attribute 'status_code':\u672a\u77e5\u9519\u8bef(\u63a5\u53e3\u8bf7\u6c42\u8d85\u65f6\u6216\u4f20\u9012\u6570\u636e\u9519\u8bef\u7b49)-400.0-Invalid request data format.-\u5bc6\u7801\u4e3anone]</name>
      <failure>
        <message>AssertionError: assert -1 == 400.0</message>
        <stack-trace>act_code = -1
act_msg = "'NoneType' object has no attribute 'status_code':未知错误(接口请求超时或传递数据错误等)"
exp_code = 400.0, exp_msg = 'Invalid request data format.'
case_name = '密码为none'

    @allure.feature(sheet.name)  # @allure.feature('（Feature1特征）')
    @pytest.mark.parametrize('act_code, act_msg, exp_code, exp_msg, case_name', ResultParam(idx).value)
    def test_fn(act_code, act_msg, exp_code, exp_msg, case_name):
&gt;       assert act_code == exp_code
E       assert -1 == 400.0

initTest.py:21: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="feature" value="login"/>
        <label name="severity" value="normal"/>
        <label name="thread" value="4244-MainThread"/>
        <label name="host" value="USER-20150424AG"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1496309864747" status="failed" stop="1496309864753">
      <name>test_case_login[-1-'NoneType' object has no attribute 'status_code':\u672a\u77e5\u9519\u8bef(\u63a5\u53e3\u8bf7\u6c42\u8d85\u65f6\u6216\u4f20\u9012\u6570\u636e\u9519\u8bef\u7b49)-400.0-Invalid request data format.-\u7528\u6237\u540d\u4e3a\u7a7a]</name>
      <failure>
        <message>AssertionError: assert -1 == 400.0</message>
        <stack-trace>act_code = -1
act_msg = "'NoneType' object has no attribute 'status_code':未知错误(接口请求超时或传递数据错误等)"
exp_code = 400.0, exp_msg = 'Invalid request data format.', case_name = '用户名为空'

    @allure.feature(sheet.name)  # @allure.feature('（Feature1特征）')
    @pytest.mark.parametrize('act_code, act_msg, exp_code, exp_msg, case_name', ResultParam(idx).value)
    def test_fn(act_code, act_msg, exp_code, exp_msg, case_name):
&gt;       assert act_code == exp_code
E       assert -1 == 400.0

initTest.py:21: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="feature" value="login"/>
        <label name="severity" value="normal"/>
        <label name="thread" value="4244-MainThread"/>
        <label name="host" value="USER-20150424AG"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1496309864754" status="failed" stop="1496309864759">
      <name>test_case_login[-1-'NoneType' object has no attribute 'status_code':\u672a\u77e5\u9519\u8bef(\u63a5\u53e3\u8bf7\u6c42\u8d85\u65f6\u6216\u4f20\u9012\u6570\u636e\u9519\u8bef\u7b49)-400.0-Invalid request data format.-\u5bc6\u7801\u4e3a\u7a7a]</name>
      <failure>
        <message>AssertionError: assert -1 == 400.0</message>
        <stack-trace>act_code = -1
act_msg = "'NoneType' object has no attribute 'status_code':未知错误(接口请求超时或传递数据错误等)"
exp_code = 400.0, exp_msg = 'Invalid request data format.', case_name = '密码为空'

    @allure.feature(sheet.name)  # @allure.feature('（Feature1特征）')
    @pytest.mark.parametrize('act_code, act_msg, exp_code, exp_msg, case_name', ResultParam(idx).value)
    def test_fn(act_code, act_msg, exp_code, exp_msg, case_name):
&gt;       assert act_code == exp_code
E       assert -1 == 400.0

initTest.py:21: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="feature" value="login"/>
        <label name="severity" value="normal"/>
        <label name="thread" value="4244-MainThread"/>
        <label name="host" value="USER-20150424AG"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1496309864760" status="failed" stop="1496309864766">
      <name>test_case_login[-1-'NoneType' object has no attribute 'status_code':\u672a\u77e5\u9519\u8bef(\u63a5\u53e3\u8bf7\u6c42\u8d85\u65f6\u6216\u4f20\u9012\u6570\u636e\u9519\u8bef\u7b49)-400.0-Invalid request data format.-\u7528\u6237\u540d\u5b57\u6bb5\u7f3a\u5931]</name>
      <failure>
        <message>AssertionError: assert -1 == 400.0</message>
        <stack-trace>act_code = -1
act_msg = "'NoneType' object has no attribute 'status_code':未知错误(接口请求超时或传递数据错误等)"
exp_code = 400.0, exp_msg = 'Invalid request data format.'
case_name = '用户名字段缺失'

    @allure.feature(sheet.name)  # @allure.feature('（Feature1特征）')
    @pytest.mark.parametrize('act_code, act_msg, exp_code, exp_msg, case_name', ResultParam(idx).value)
    def test_fn(act_code, act_msg, exp_code, exp_msg, case_name):
&gt;       assert act_code == exp_code
E       assert -1 == 400.0

initTest.py:21: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="feature" value="login"/>
        <label name="severity" value="normal"/>
        <label name="thread" value="4244-MainThread"/>
        <label name="host" value="USER-20150424AG"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1496309864767" status="failed" stop="1496309864771">
      <name>test_case_login[-1-'NoneType' object has no attribute 'status_code':\u672a\u77e5\u9519\u8bef(\u63a5\u53e3\u8bf7\u6c42\u8d85\u65f6\u6216\u4f20\u9012\u6570\u636e\u9519\u8bef\u7b49)-400.0-Invalid request data format.-\u5bc6\u7801\u5b57\u6bb5\u7f3a\u5931]</name>
      <failure>
        <message>AssertionError: assert -1 == 400.0</message>
        <stack-trace>act_code = -1
act_msg = "'NoneType' object has no attribute 'status_code':未知错误(接口请求超时或传递数据错误等)"
exp_code = 400.0, exp_msg = 'Invalid request data format.', case_name = '密码字段缺失'

    @allure.feature(sheet.name)  # @allure.feature('（Feature1特征）')
    @pytest.mark.parametrize('act_code, act_msg, exp_code, exp_msg, case_name', ResultParam(idx).value)
    def test_fn(act_code, act_msg, exp_code, exp_msg, case_name):
&gt;       assert act_code == exp_code
E       assert -1 == 400.0

initTest.py:21: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="feature" value="login"/>
        <label name="severity" value="normal"/>
        <label name="thread" value="4244-MainThread"/>
        <label name="host" value="USER-20150424AG"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
